name: Release 
on:
  push:
    tags:
      - '**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
        DOCKER_Repo: docker pull saadmtsa/devops_docker_demo_palestine

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
            DOCKER_USERNAME: alezz77122
            DOCKER_PASSWARD: ${{ secrets.DOCKER_PASSWARD }}
        run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWARD
      - name: Docker Build Image
        run: | 
            version=${GITHUB_REF##*/}
            docker bulid . -t $DOCKER_Repo:$version
      - name: Docker push
        run: |
            version=${GITHUB_REF##*/}
            docker push $DOCKER_Repo:$version               

      - name: Build project
        run: |
          # Add your build commands here
          # For example, if you're using a Node.js project:
          # npm install
          # npm run build

      - name: Deploy to production
        run: |
          # Add your deployment commands here
          # For example, if you're deploying to a server:
          # ssh user@server 'deploy.sh'